### ISSUE TITLE
lostFocus принуждает все контролы, даже неактивные

### ISSUE THREAD

**Issue by Philosoph228** [Aragajaga/CrossZero#15]
Каждое событие мыши на кнопке вызывает onMouseLeave на остальные контролы не в фокусе.
Пример кнопки. На каждый `onMouseLeave` вызывается `FadeAnimation::Play`:
Лог:
```
[ON MOUSE ENTER]
[FadeAnimation] Start playing
[FadeAnimation] Start playing
[FadeAnimation] Start playing
[FadeAnimation] Start playing
[FadeAnimation] Start playing
[FadeAnimation] Start playing
[FadeAnimation] Start playing
[FadeAnimation] Start playing
```
backtrace из gdb:
```
#0  FadeAnimation::play (this=0x22f7d0, destColor=...)
    at C:/Users/User/Desktop/CrossZero/src/animation.hpp:72
#1  0x000000000040203b in UI::Controls::Button::onMouseLeave (this=0x22f628)
    at C:/Users/User/Desktop/CrossZero/src/button.cpp:133
#2  0x00000000004113e0 in MouseEventSubject::lostFocus (this=0x22f598)
    at C:/Users/User/Desktop/CrossZero/src/mouse_event.hpp:107
#3  0x00000000004036c0 in UI::Screen::Base::lostFocus (this=0x22f590)
    at C:/Users/User/Desktop/CrossZero/src/screen.cpp:35
#4  0x0000000000411c4b in UI::Screen::ScreenManager::postEvent (
    this=0x8dad00, evt=...)
    at C:/Users/User/Desktop/CrossZero/src/screen.hpp:54
#5  0x00000000004074ca in main (argc=1, argv=0x98ac60)
    at C:/Users/User/Desktop/CrossZero/src/main.cpp:152
```

**Comment by Philosoph228** [comment]
Значит потеря фокуса применима только к тем контролам, где фокус в настоящее время есть.
